#!/bin/bash
# description: Tomcat Start Stop Restart
# processname: tomcat
# chkconfig: 234 20 80
JAVA_HOME=/usr/lib/jvm/jre/
export JAVA_HOME
PATH=$JAVA_HOME/bin:$PATH
export PATH
export ip=`ifconfig eth0 |grep "inet addr" |awk '{print $2}' |awk -F: '{print $2}'`

export CATALINA_HOME=/opt/entermedia/tomcat
export CATALINA_BASE=/opt/entermedia/tomcat
#export CATALINA_BASE
#export CATALINA_HOME
startup=$CATALINA_HOME/bin/startup.sh
shutdown=$CATALINA_HOME/bin/shutdown.sh
TOMCAT7_USER=entermedia
TOMCAT7_GROUP=entermedia
export TOMCAT7_USER
export TOMCAT7_GROUP

##is this needed?
export JRE_HOME=/usr/lib/jvm/jre/
JAVA_OPTS="-Djava.awt.headless=true -Xmx128M"
export JAVA_OPTS

POLICY_CACHE="$CATALINA_BASE/work/catalina.policy"

if [ -z "$CATALINA_TMPDIR" ]; then
        CATALINA_TMPDIR="$JVM_TMP"
fi

# Set the JSP compiler if set in the tomcat7.default file
if [ -n "$JSP_COMPILER" ]; then
        JAVA_OPTS="$JAVA_OPTS -Dbuild.compiler=\"$JSP_COMPILER\""
fi

SECURITY=""
if [ "$TOMCAT7_SECURITY" = "yes" ]; then
        SECURITY="-security"
fi

# Define other required variables
CATALINA_PID="/var/run/$NAME.pid"
CATALINA_SH="$CATALINA_HOME/bin/catalina.sh"

if [ -z "${JSSE_HOME}" -a -r "${JAVA_HOME}/jre/lib/jsse.jar" ]; then
    JSSE_HOME="${JAVA_HOME}/jre/"
fi


case $1 in
start)
su $TOMCAT7_USER -l -c $startup
/sbin/iptables -t nat -A OUTPUT -d localhost -p tcp --dport 80 -j REDIRECT --to-ports 8080
/sbin/iptables -t nat -A OUTPUT -d $ip -p tcp --dport 80 -j REDIRECT --to-ports 8080
/sbin/iptables -t nat -A PREROUTING -d $ip -p tcp --dport 80 -j REDIRECT --to-ports 8080
;; 
stop)   
su $TOMCAT7_USER -c  $shutdown
/sbin/iptables -t nat -D OUTPUT -d localhost -p tcp --dport 80 -j REDIRECT --to-ports 8080
/sbin/iptables -t nat -D OUTPUT -d $ip -p tcp --dport 80 -j REDIRECT --to-ports 8080
/sbin/iptables -t nat -D PREROUTING -d $ip -p tcp --dport 80 -j REDIRECT --to-ports 8080
;; 
restart)
/sbin/iptables -t nat -D OUTPUT -d localhost -p tcp --dport 80 -j REDIRECT --to-ports 8080
/sbin/iptables -t nat -D OUTPUT -d $ip -p tcp --dport 80 -j REDIRECT --to-ports 8080
/sbin/iptables -t nat -D PREROUTING -d $ip -p tcp --dport 80 -j REDIRECT --to-ports 8080
su $TOMCAT7_USER -c  $shutdown
su $TOMCAT7_USER -l -c $startup
#/sbin/iptables -t nat -A OUTPUT -d localhost -p tcp --dport 80 -j REDIRECT --to-ports 8080
#/sbin/iptables -t nat -A OUTPUT -d $ip -p tcp --dport 80 -j REDIRECT --to-ports 8080
#/sbin/iptables -t nat -A PREROUTING -d $ip -p tcp --dport 80 -j REDIRECT --to-ports 8080
;; 
esac    
exit 0
